name: ozvm
version: "1.3.0b1"
summary: A Cambridge Z88 Emulator
description: A Cambridge Z88 Emulator
grade: devel
confinement: devmode

apps:
    ozvm:
        command: java -jar -Duser.home=$SNAP_USER_DATA $SNAP/usr/ozvm/z88.jar
        plugs: [x11]
        environment:
            JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-$SNAP_ARCH
            PATH: $JAVA_HOME/jre/bin:$SNAP/usr/bin/:$PATH
            XDG_DATA_HOME: $SNAP/usr/share
            FONTCONFIG_PATH: $SNAP/etc/fonts/config.d
            FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

parts:
    ozvm:
        source: http://gitlab.com/z88/ozvm/repository/V1.3.0b1/archive.zip
        plugin: dump
        build-packages: [default-jdk]
        stage-packages: [default-jre]
        build: |
            cd ozvm-V*
            chmod +x ./makejar.sh
            ./makejar.sh
        install: |
            cd ozvm-V*
            mv z88.jar $SNAPCRAFT_PART_INSTALL
            cp -r roms $SNAPCRAFT_PART_INSTALL
        organize:
            z88.jar: usr/ozvm/z88.jar
            roms/ : usr/ozvm/roms/
        stage:
            - usr/ozvm/z88.jar
            - usr/ozvm/roms/
        prime:
            - usr/ozvm/z88.jar
            - usr/ozvm/roms/

    launcher:
        source: .
        plugin: dump
        # Need to stage default-jre here.
        # Why doesn't it accept its being staged in ozvm part?
        stage-packages: [default-jre]

